app/models.py
import datetime

from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app
from flask.ext.login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from . import db, login_manager


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(120))
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    links = db.relationship('Link', backref='user', lazy='dynamic')
    confirmed = db.Column(db.Boolean, default=False)
    first_name = db.Column(db.String(120))
    last_name = db.Column(db.String(120))

    def __repr__(self):
        return '<User %r>' % (self.email)

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def generate_confirmation_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'confirm': self.id})

    def confirm(self, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        if data.get('confirm') != self.id:
            return False
        self.confirmed = True
        db.session.add(self)
        db.session.commit()
        return True

    def generate_reset_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'reset': self.id})

    def reset_password(self, token, new_password):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        if data.get('reset') != self.id:
            return False
        self.password = new_password
        db.session.add(self)
        return True

    def generate_email_change_token(self, new_email, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'change_email': self.id, 'new_email': new_email})

    def change_email(self, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        if data.get('change_email') != self.id:
            return False
        new_email = data.get('new_email')
        if new_email is None:
            return False
        if self.query.filter_by(email=new_email).first() is not None:
            return False
        self.email = new_email
        db.session.add(self)
        return True


@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))


class Link(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(120))
    url = db.Column(db.String(240), unique=True)
    date = db.Column(db.Date, index=True)
    seen = db.Column(db.Boolean, default=False)
    image = db.Column(db.String(240))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return '<Link %r>' % (self.name)

app/main/forms.py
from flask.ext.wtf import Form
from wtforms import (StringField, TextAreaField, BooleanField, SelectField,
                     SubmitField)
from wtforms.validators import Required, Length, Email, Regexp
from wtforms import ValidationError

from ..models import User


class EditProfileForm(Form):
    username = StringField('Username', validators=[Length(0, 120)])
    first_name = StringField('First Name', validators=[Length(0, 120)])
    last_name = StringField('Last Name', validators=[Length(0, 120)])
    submit = SubmitField('Submit')

app/__init__.py
import os

from config import basedir
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.login import LoginManager
from flask.ext.mail import Mail
from flask.ext.sqlalchemy import SQLAlchemy


app = Flask(__name__)
app.config.from_object('config')
db = SQLAlchemy(app)
bootstrap = Bootstrap(app)
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'auth.login'
mail = Mail(app)

from .auth import auth as auth_blueprint
from .main import main as main_blueprint

app.register_blueprint(main_blueprint)
app.register_blueprint(auth_blueprint, url_prefix='/auth')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import (render_template, flash, redirect, session, url_for, request,
                   jsonify, current_app, g)
from flask.ext.login import current_user, login_required
from sqlalchemy.exc import IntegrityError

from . import main
from .. import db
from ..models import Link, User
from ..tasks import send_email
from .crawler import crawler
from .forms import EditProfileForm


@main.route('/')
@main.route('/index')
def index():
    return render_template("index.html")


@main.route('/user/<username>')
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    pagination = user.links.order_by(Link.date.desc()).filter_by(seen=False).paginate(
        page, per_page=current_app.config['LINKS_PER_PAGE'],
        error_out=False)
    links = pagination.items
    return render_template('user.html', user=user, links=links,
                           pagination=pagination)
    return render_template('user.html', user=user)

@main.route('/userdata/<username>')
@login_required
def user_data(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    pagination = user.links.order_by(Link.date.desc()).filter_by(seen=False).paginate(
        page, per_page=current_app.config['LINKS_PER_PAGE'],
        error_out=False)
    links = []
    for item in pagination.items:
        links.append({'id': item.id, 'name': item.name, 'url': item.url, 'date': item.date.isoformat()})
    if user == current_user:
        return jsonify({'links':links, 'is_user':True})
    return jsonify({'links':links, 'is_user':False})


@main.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        db.session.add(current_user)
        db.session.commit()
        flash('Your profile has been updated.')
        return redirect(url_for('main.user', username=current_user.username))
    form.username.data = current_user.username
    form.first_name.data = current_user.first_name
    form.last_name.data = current_user.last_name
    return render_template('edit_profile.html', form=form)


@main.route('/crawl/<username>')
def crawl(username):
    results = []
    user = User.query.filter_by(username=username).first_or_404()
    for result in crawler():
        name, url, image, date = result
        link = Link(name=name, url=url, image=image, date=date, user_id=user.id, seen=False)
        try:
            db.session.add(link)
            db.session.commit()
        except IntegrityError:
            db.session.rollback()
        else:
            results.append({'name': name, 'url': url, 'image': image,
                            'date': date.isoformat()})
    if results:
        send_email(user.email, 'You got some new episodes', 'email/episodes',
                   user=user, results=results)
    return jsonify({'results': results})


@main.route('/delete-links', methods=['POST'])
@login_required
def delete_links():
    link_ids = request.form['selected'].split(',')
    print(link_ids)
    if link_ids is None:
        flash('Links not found.')
        return redirect(url_for('main.user', username=current_user.username))
    links = Link.query.filter(Link.id.in_(link_ids)) #.delete()
    for link in links:
        db.session.delete(link)
    db.session.commit()
    flash('Your links have been deleted.')
    return redirect(url_for('main.user', username=current_user.username))


@main.route('/set-seen', methods=['POST'])
@login_required
def set_seen():
    link_ids = request.form['selected'].split(',')
    if not link_ids:
        flash('Links not found.')
        return redirect(url_for('main.user', username=current_user.username))
    links = Link.query.filter(Link.id.in_(link_ids))
    for link in links:
        link.seen = True
        db.session.add(link)
    db.session.commit()
    flash('Your links have been set to  seen.')
    return redirect(url_for('main.user', username=current_user.username))

app/templates/_links.html
<table class="table table-striped table-bordered todolist">
	{% for link in links %}
		<tr>
			{% if user == current_user %}
			<td style="text-align:center;" class="col-md-2"><input type="checkbox" value="{{ link.id }}" name="link"/></td>
			{% endif %}
			<td class="col-md-8"><a href="{{ link.url }}">{{ link.name }}</a></td>
			<td style="text-align:center;" class="col-md-2">{{ link.date }}</td>
		</tr>
	{% endfor %}
</table>

app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% block title %}ToWatchList{% endblock %}

{% block head %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}

{% block navbar %}
	<div class="navbar navbar-inverse" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/">ToWatchList</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a href="/">Home</a></li>
					{% if current_user.is_authenticated %}
	                	<li><a href="{{ url_for('main.user', username=current_user.username) }}">Profile</a></li>
	                {% endif %}
				</ul>
			<ul class="nav navbar-nav navbar-right">
				{% if current_user.is_authenticated %}
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="{{ url_for('auth.change_password') }}">Change Password</a></li>
							<li><a href="{{ url_for('auth.change_email_request') }}">Change Email</a></li>
							<li><a href="{{ url_for('auth.logout') }}">Sign Out</a></li>
						</ul>
					</li>
				{% else %}
				<li><a href="{{ url_for('auth.register') }}">Sign Up</a></li>
				<li><a href="{{ url_for('auth.login') }}">Sign In</a></li>
				{% endif %}
			</ul>
			</div>
		</div>
	</div>
{% endblock %}
{% block content %}
<div class="container">
	{% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
	{% block page_content %}{% endblock %}
</div>
{% endblock %}

app/templates/change_email.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}ToWatchList - Change Email Address{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Change Your Email Address</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/change_password.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}ToWatchList - Change Password{% endblock %}
{% block page_content %}
  <div class="page-header">
    <h1>Change your Password</h1>
  </div>
  <div class="col-md-4">
    {{ wtf.quick_form(form, button_map={"submit": "primary"}) }}
  </div>
{% endblock %}

app/templates/edit_profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}ToWatchList - Edit Profile{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Edit Your Profile</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form, button_map={"submit": "primary"}) }}
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

    {% block content %}
        <div class="container">
            <div class="page-header">
                <h1>Hello, 
                    {% if current_user.is_authenticated %}
                        {{ current_user.username }}
                    {% endif %}
                </h1>
            </div>
        </div>
    {% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}ToWatchList - Login{% endblock %}
{% block page_content %}
  <div class="page-header">
    <h1>Login</h1>
  </div>
  <div class="col-md-4">
    {{ wtf.quick_form(form, button_map={"submit": "primary"}) }}
    <br>
    <p>Forgot your password? <a href="{{ url_for('auth.password_reset_request') }}">Click here to reset it</a>.</p>
    <p>New user? <a href="{{ url_for('auth.register') }}">Click here to register</a>.</p>
  </div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}ToWatchList - Register{% endblock %}
{% block page_content %}
  <div class="page-header">
    <h1>Register</h1>
  </div>
  <div class="col-md-4">
    {{ wtf.quick_form(form, button_map={"submit": "primary"}) }}
  </div>
{% endblock %}

app/templates/reset_password.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}ToWatchList - Password Reset{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Reset Your Password</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form, button_map={"submit": "primary"}) }}
</div>
{% endblock %}

app/templates/unconfirmed.html
{% extends "base.html" %}

{% block title %}ToWatchList - Confirm your accont{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>
        Hello, {{ current_user.username }}!
    </h1>
    <h3>You have not confirmed your account yet.</h3>
    <p>
        Before you can access this site you need to confirm your account.
        Check your inbox, you should have received an email with a confirmation link.
    </p>
    <p>
        Need another confirmation email?
        <a href="{{ url_for('auth.resend_confirmation') }}">Click here</a>
    </p>
</div>
{% endblock %}

app/templates/user.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block page_content %}
<div class="page-header">
    <h1>{{ user.username }}</h1>
    {% if user.first_name and user.last_name %}
    <p>
        {{ user.first_name }} {{ user.last_name }}
    </p>
    <p>
        {{ user.links.count() }} links to watch
    </p>
    {% endif %}
    <p>
        {% if user == current_user %}
            <a class="btn btn-primary" href="{{ url_for('main.edit_profile') }}">Edit Profile</a>
        {% endif %}
    </p>
</div>
<div class="container">
    <div class="row col-md-2">
    </div>
    <div class="row col-md-8" id="links">
        <h3>
            Links to Watch
        </h3>
        {% if user == current_user %}
            <div class="btn-toolbar">
                <button type="button" class="btn btn-primary" onclick="onClickSeen()" id="seen" disabled>Mark as Seen</button>
                <button type="button" class="btn btn-danger" onclick="onClickDelete()" id="delete" disabled>Delete</button>
            </div>
        {% endif %}
        <br>
        <table class="table table-striped table-bordered todolist">
    
        </table>
        <!-- {% include '_links.html' %} -->
        <!-- {% if pagination %}
            <div class="pagination">
                {{ macros.pagination_widget(pagination, 'main.user', username=user.username) }}
            </div>
        {% endif %} -->
    </div>
    <div class="row col-md-2">
    </div>
</div>
{% endblock %}
{% block scripts %}
{{ super() }}
<script type="text/javascript" src="{{ url_for('static', filename='towatchlist.js') }}"></script>
{% endblock %}